# Configuration for Netlify in the functions directory
# Explicitly exclude configuration files from being deployed as functions

[functions]
  # Include only files that are actual serverless functions
  included_files = ["src/**/*.js", "src/**/*.ts"]
  
  # Exclude configuration files and node_modules
  excluded_files = [
    "*.config.js",
    "eslint-config.js",
    "eslintrc-config.js",
    "tsconfig*.json",
    "package.json",
    "package-lock.json",
    "**/node_modules/**/.eslintrc",
    "**/node_modules/**/.eslintrc.js",
    "**/node_modules/**/.eslintrc.yml",
    "**/node_modules/**/.eslintrc.json",
    "**/node_modules/**/*"
  ] 