# Configuration for Netlify in the functions directory
# Explicitly exclude configuration files from being deployed as functions

[functions]
  # Include only files that are actual serverless functions
  included_files = ["src/**/*.js", "src/**/*.ts"]
  
  # Exclude configuration files and node_modules
  excluded_files = [
    "*.config.js",
    "eslintrc-config.js",
    "*eslintrc*",
    "tsconfig*.json",
    "package.json",
    "package-lock.json",
    ".netlify.toml",
    "node_modules/**/*"
  ] 