[build]
  command = "npm install && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "npm run dev:frontend"
  port = 3000
  targetPort = 3000
  publish = "dist/public"
  autoLaunch = true

[functions]
  directory = "functions/src"
  node_bundler = "esbuild"
  included_files = ["functions/src/**/*.js", "functions/src/**/*.ts"]
  excluded_files = ["**/node_modules/**/.eslintrc*"]
  external_node_modules = ["node-fetch"]

# First, add a redirect for functions with a higher priority
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Then add the catch-all redirect for the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 