[build]
  command = "npm install && npm run build"
  publish = "dist/public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "npm run dev:frontend"
  port = 3000
  targetPort = 3000
  publish = "dist/public"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 