[build]
  command = "npm install && npm run build"
  publish = "dist/public"
  functions = "functions/src"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  command = "npm run dev:frontend"
  port = 3000
  targetPort = 3000
  publish = "dist/public"
  autoLaunch = true

[functions]
  directory = "functions/src"
  node_bundler = "esbuild"
  included_files = [
    "functions/src/**/*.js",
    "functions/src/**/*.ts"
  ]

[functions.excluded_files]
  patterns = [
    "**/node_modules/**",
    "**/.git/**",
    "**/README.md",
    "**/package.json",
    "**/package-lock.json",
    "**/*.config.js",
    "**/*.test.js",
    "**/*.spec.js",
    "**/.eslintrc*",
    "**/tsconfig*.json"
  ]

[functions.external_node_modules]
  - "node-fetch"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 